[workspace]
resolver = "3"
members = ["corofy",
    "delayserver", "event_queue", "futures", "join", "pinning", "runtime", "runtime_with_waker",
]

[workspace.dependencies]
mio = { version = "0.8.8", features = ["net", "os-poll"] }
